import "./App.css";
import { useRef, useEffect } from "react";

let frequency = 1;
let frequency2 = 1;
let increment = 0.05;
let increment2 = 0.00005;

/**
 * @param {CanvasRenderingContext2D} ctx
 * @param {number} width
 * @param {number} height
 */
function draw(ctx, width, height) {
    frequency += increment;
    if (frequency > 5 || frequency < 1) {
        increment *= -1;
    }

    frequency2 += increment2;
    if (frequency2 > 5 || frequency2 < 1) {
        increment2 *= -1;
    }

    for (let i = 0; i < width; i++) {
        let y = Math.tan(Math.sin(i / 50) * frequency) + height / 2;
        y *= Math.sin((i / 5) * frequency2);

        ctx.fillStyle = "black";
        ctx.fillRect(i, y, 3, 2);
    }
}

function App() {
    const canvasRef = useRef();

    useEffect(() => {
        const canvas = canvasRef.current;
        const ctx = canvas.getContext("2d");
        const render = () => {
            if (!ctx) {
                return;
            }
            canvas.width = window.innerWidth * 0.8;
            canvas.height = window.innerHeight * 0.8;
            draw(ctx, canvas.width, canvas.height);
        };

        render();
        const interval = setInterval(render, 100);
        window.addEventListener("resize", render);

        return () => {
            window.removeEventListener("resize", render);
            clearInterval(interval);
        };
    }, []);

    return (
        <div className="App">
            <header>
                <h1>Hello Wurld</h1>
            </header>
            <main>
                <section>
                    <p>
                        Lorem ipsum is placeholder text commonly used in the
                        graphic, print, and publishing industries for previewing
                        layouts and visual mockups. This text was generated by
                        Github Copilot.
                    </p>
                    <br></br>
                    <a href="https://copilot.github.com/">
                        Learn more about github Copilot here
                    </a>
                    <h2>Here's a canvas drawing</h2>
                    <canvas ref={canvasRef}></canvas>
                </section>
            </main>
        </div>
    );
}

export default App;
